#!/usr/bin/env bash
set -eu
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$dir"

cargo fmt -- --check

cargo build --release

cp "${CARGO_TARGET_DIR:-./target}/release/abav1" ~/bin/abav1
strip ~/bin/abav1

ls -lh ~/bin/abav1
